### PR TITLE
add html handling in native types

### PR DESCRIPTION
**Pull request by maxired**
This PR solves https://github.com/react-dnd/react-dnd/issues/2928 and allows to drag and drop HTML elements such as images from another tab.

This PR does not implements any custom logic to deal with the HTML data in itself.

### CODE REVIEW

**Comment by maxired** [comment]
@darthtrevino do you have any opinion about this ?

**Comment by darthtrevino** [comment]
I apologize, I've been a beet slammed at work. Just taking a quick look - Is the preventDefault() necessary()? At some point we removed some of that because we didn't want to interfere with custom handling of native events. Also, can you put together an example on the docsite using this new type? You can base it off of the existing native types example or just extend it if you prefer

**Comment by maxired** [comment]
Thanks for your answer. Yes I will try to setup an example.

Without the preventDefault, the browser opens the content in a new tab in that case. I am not very familiar with this code base, so maybe it can be put somewhere else? As a side not, I did not saw side effects on other handlers.

**Comment by maxired** [comment]
@darthtrevino I've just added an example, please let me know if this looks good to you.

**Comment by maxired** [comment]
@darthtrevino sorry to bother you. What is the status on this one ?

**Comment by darthtrevino** [comment]
Hey Maxence,
Again, apologies for the delay. I went ahead and merged it, I'll work on
stabilizing the main branch and preparing for a release.

**Comment by inukshuk** [comment]
This PR raises a problem: dragged images, URLs, and links etc. typically have multiple data transfer items with type `text/html` and `text/uri-list` and even `text/plain`. Right now it seems that [matchNativeItemType](https://github.com/react-dnd/react-dnd/blob/main/packages/backend-html5/src/NativeDragSources/index.ts#L13) returns just the first match: that means for example that dragged images or URLs are now only matched as type `HTML`, because it was added higher up in the native types config. For this reason, this PR makes it impossible (I believe?) to register drop targets for URLs -- unless you register for type HTML and then parse out the URL from the HTML data.

**Pull request merged**
