### PR TITLE
Fix : Repair module lost errors

### PR DESCRIPTION
**Pull request by abnerCrack**

### CODE REVIEW

**Comment by darthtrevino** [comment]
What was the error that you were running into?

**Comment by abnerCrack** [comment]
when i run npm run start ,i get this error.

error info:
```
ERROR in ./packages/react-dnd/src/decorateHandler.js
Module not found: Error: Cannot resolve module 'disposables' in /Users/xxxxxxxx/Desktop/react-dnd/packages/react-dnd/src
 @ ./packages/react-dnd/src/decorateHandler.js 23:19-41
```

**Comment by darthtrevino** [comment]
I'm having a hard time reproducing this issue. What version of NodeJS and Yarn are you using? Are you installing dependencies with yarn?

**Comment by abnerCrack** [comment]
node version: v7.1.0
npm version :3.10.9
method:   npm install
I think there may be cached, you can try to run rm -r node_modules.

**Comment by darthtrevino** [comment]
This project is using Yarn to install dependencies.

**Pull request closed without merging**
