### PR TITLE
fix tab indents and remove redundant comma

### PR DESCRIPTION
**Pull request by hiromoon**
I replaced tab indent to space, and remove redundant comma, in the tutorial code.

### CODE REVIEW

**Comment by darthtrevino** [comment]
Thanks for the PR! The formatting of this file is handled by Prettier, and we use tabs and trailing commas in this project by default. Prettier will let you do overrides, and it may be worth considering using spaces and disabling trailing-commas in markdown, but that will be a broader change.

**Comment by darthtrevino** [comment]
To follow up on this, it looks like that should've been the case. I'll add some formatting assertion to our testing pipeline.

**Comment by darthtrevino** [comment]
https://github.com/react-dnd/react-dnd/pull/2464

**Comment by hiromoon** [comment]
@darthtrevino 
Thank you for review.

I'm sorry  if I misunderstanding, for I'm not good at English.
I looks like that #2464 doesn't includes this PR changes.
master branch is not changed.
スクリーンショット 2020-05-22 5 48 41

I try to run `yarn lint:formatting`, but there probrems aren't resolved.
```
$ yarn lint:formatting packages/documentation/docsite/markdown/docs/00\ Quick\ Start/Tutorial.md
yarn run v1.21.1
$ pretty-quick --check 'packages/documentation/docsite/markdown/docs/00 Quick Start/Tutorial.md'
🔍  Finding changed files since git revision 4ad004c1a.
🎯  Found 0 changed files.
✅  Everything is awesome!
✨  Done in 0.80s.
```

I think that I fixed `redundant comma` isn't a trailling comma, but a syntax error, isn't it?

**Comment by darthtrevino** [comment]
I see, the formatting check did not remove the trailing commas. It looks like manually removing them doesn't cause the formatter to fail, so I think I'm okay with this

**Comment by hiromoon** [comment]
Thank you for rereview.

**Pull request merged**
