### PR TITLE
Testing.md: React Testing Library & React DnD Chessboard Example

### PR DESCRIPTION
**Pull request by ryota-murakami**
[Original PR](https://github.com/react-dnd/react-dnd/pull/2729) was failed CI at `lint:spelling`, I'm sorry about it.
I fixed it and then submit PR again.

Please review whenever you have time. 🙇‍♂️

Thank you maintaining continually awesome library!

### CODE REVIEW

**Comment by darthtrevino** [comment]
Thanks for the PR, Ryota! 

The Chessboard Example can be found in this repo in two places, one with a hooks-based implementation, and one with a decorators-based implementation:

https://github.com/react-dnd/react-dnd/tree/main/packages/documentation/examples-hooks/src/00-chessboard
https://github.com/react-dnd/react-dnd/tree/main/packages/documentation/examples-decorators/src/00-chessboard

If you want to run the chessboard app, you can fire up the CRATester app and select it from among other examples:
https://github.com/react-dnd/react-dnd/tree/main/packages/documentation/cra-test

I don't mind adding links to the example code in our documentation, but I would prefer to keep the links _internal_ to the repository, or at least to the react-dnd org.

**Comment by ryota-murakami** [comment]
Thank you for polite response! @darthtrevino

> The Chessboard Example can be found in this repo in two places, one with a hooks-based implementation, and one with a decorators-based implementation:
> https://github.com/react-dnd/react-dnd/tree/main/packages/documentation/examples-hooks/src/00-chessboard
https://github.com/react-dnd/react-dnd/tree/main/packages/documentation/examples-decorators/src/00-chessboard

Yes actually my repo code is copy of your hook based example https://github.com/react-dnd/react-dnd/tree/main/packages/documentation/examples-hooks/src/00-chessboard

and added small edit such as `test-id`, [releaseObserver()](https://github.com/laststance/react-testing-library-react-dnd-chessboard-example/blob/f14b54c47d03fc00a9c4c39ab4824f84969e1695/src/Game.ts#L48-L53) in order to clear all state each test like this...

```javascript
beforeEach(() => {
  /*
   * Every time Knight initial position: "57"
   * and Knight droppable positions are "40", "42", "51"
   * when you got all cells with screen.getAllByRole('gridcell')
   */
  observe((knightPosition: KnightPosition) =>
    render(<Board knightPosition={knightPosition} />)
  )
})

afterEach(() => {
  releaseObserver()
})
```

　

>  I would prefer to keep the links internal to the repository, or at least to the react-dnd org.

Sure! 
I'm going to add React DnD repo's link to README and add following copyright text into the all Chessboard app code files.  
Would you mind any points that should be fixexd?

```javascript
/**
 * Copyright (c) The code is copy & modified from original(https://github.com/react-dnd/react-dnd/tree/abd3132710bde6ce065aef9d0c50b2d5f8823598/packages/documentation/examples-hooks).
 * Dan Abramov <dan.abramov@me.com> (http://github.com/gaearon)
 * Chris Trevino <darthtrevino@gmail.com> (http://github.com/darthtrevino)
 * Jordan Gensler (http://github.com/kesne)
 * Gagan (https://github.com/thetechie)
 *
 * The MIT License (MIT)(https://github.com/react-dnd/react-dnd/blob/abd3132710bde6ce065aef9d0c50b2d5f8823598/LICENSE)
 */
```

**Comment by ryota-murakami** [comment]
@darthtrevino I'm afraid asking bother question. 😅

Now I 

- [added React DnD official doc on README](https://github.com/laststance/react-testing-library-react-dnd-chessboard-example#-chessboard-app--source-from-react-dnd-official-document-)

**Comment by darthtrevino** [comment]
Hey Ryota, 
Don't worry, it's no bother at all 😀. Life has been kind of nuts in the past couple of weeks. I'll take a look at this this weekend.

**Comment by darthtrevino** [comment]
The testing-library piece here is pretty great. I was wrestling a bit today with how to modernize the testing, and this approach is very clear

**Comment by darthtrevino** [comment]
@ryota-murakami  - I'm going to close this PR out in favor of #3025 . I think the biggest benefit we gain here is from improving our testing patterns. Really fantastic job on that. I think this will help to elevate the testing on this project overall.

**Pull request closed without merging**
