### PR TITLE
Add React 16 to peer dependencies

### PR DESCRIPTION
**Pull request by renchap**
React 16 (Fiber) is now in beta: https://github.com/facebook/react/issues/10294

It would be a good idea to allow it as a `peerDependency`.

I ran the test suite against React 16 (`npm add react@next react-dom@next && npm test`) and it did not report any failures.

I did not wanted to bump React in the main `package.json`, but I can amend the PR with it if needed.

### CODE REVIEW

**Comment by darthtrevino** [comment]
Thanks @renchap, would you be willing to update the dependencies at the top level to React 16 as part of this PR?

**Comment by renchap** [comment]
@darthtrevino Here you go, rebased against master.

I did not try to fix these NPM warnings:

```
npm WARN extract-text-webpack-plugin@2.1.2 requires a peer of webpack@^2.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-frame-component@1.1.1 requires a peer of react@^15.5.4 but none is installed. You must install peer dependencies yourself.
npm WARN react-frame-component@1.1.1 requires a peer of react-dom@^15.5.4 but none is installed. You must install peer dependencies yourself.
npm WARN react-hot-api@0.4.7 requires a peer of react@>=0.11.0 || ^0.14.0-rc but none is installed. You must install peer dependencies yourself.
```

For `react-frame-component` there is no version supporting React 16 yet. `react-hot-api` is deprecated. `extract-text-webpack-plugin` should be updated to latest version for Webpack 3 support.

**Comment by renchap** [comment]
@darthtrevino React 16 RC3 is now out, do you need any changes to this PR for it to get merged?

**Comment by darthtrevino** [comment]
Looks good; I'll cut a release tonight

**Pull request merged**
