### PR TITLE
Add example of DND where box respects parents boundaries

### PR DESCRIPTION
**Pull request by Andreyco**

### CODE REVIEW

**Comment by gaearon** [comment]
Maybe better to respect bounds in existing examples without making it configurable?
Sounds like sane behavior to me.
What do you think?

**Comment by Andreyco** [comment]
Ofc, let's make it default in examples. User will pick, what he wants. I will update examples ASAP

**Comment by Andreyco** [comment]
Examples are merged.

**Comment by globexdesigns** [comment]
You've got some minor ESLint bugs in your last commit. Can you fix those before this gets merged in? See: https://travis-ci.org/gaearon/react-dnd/builds/87365677

**Comment by Andreyco** [comment]
Sure, it's fixed.
There are more ESLint warning, not related to this PR. I will create another one for those...

**Pull request closed without merging**
