### PR TITLE
Added support for CTRL key to copy as well as ALT

### PR DESCRIPTION
**Pull request by alexmorleyfinch**
On Windows, the copy modifier key is CTRL rather than ALT. This PR allows either key to copy

### CODE REVIEW

**Comment by darthtrevino** [comment]
I'm not opposed to this, but it should only use CTRL if the platform is Windows, and ALT if on OSX or linux

**Comment by gshilin** [comment]
There is no reliable way to determine OS from  browser: [https://stackoverflow.com/questions/11219582/how-to-detect-my-browser-version-and-operating-system-using-javascript#answer-29057922](url)

**Comment by Seldaek** [comment]
`var is_OSX = !!navigator.platform.match(/(Mac|iPhone|iPod|iPad)/i);` is a fairly reliable way of detecting OSX + iOS devices. Pretty much everything else (Windows/Linux) is using CTRL key, so that seems like a reasonable way to do the check.

**Comment by megaboich** [comment]
I like this pull request, but probably it is better to think about making it configurable through some props. So it could be configured which key is going to be used as modifier key. And here I do see some lack of design - if for example I do need more than one modifier. For example I want to move an object by default, make a "link" if "Alt" is pressed and "copy" if "Ctrl" is pressed.
Also I could not find much of official documentation for this "dropEffect", all I could find is an example and it is not totally clear.

**Pull request closed without merging**
