### PR TITLE
Documentation: Add Touch Backend Flag

### PR DESCRIPTION
**Pull request by darthtrevino**
Adds a ?touch flag to the docsite to test out the TouchBackend

@longlho this has some ramifications in the TouchBackend. The next release of it will be a major release to the 8.x series though. Are there any other semver major changes you would like to make to the touchbackend?

### CODE REVIEW

**Comment by darthtrevino** [comment]
@longlho Do you have any other examples you'd like to add to the docsite that are touch-specific? We can set up another documentation section for those if so

**Comment by longlho** [comment]
Nope nothing from my side other than w/e is in the README https://github.com/redonkulus/react-dnd-touch-backend

**Comment by darthtrevino** [comment]
I'd like to clean up the factory method signature so that you don't have to have a two-step construction step for the touchBackend. This will probably be a semver major, but I think it will be a conceptual improvement.

**Comment by longlho** [comment]
SGTM

**Pull request merged**
