### PR TITLE
Update docs about Custom drag preview implementation

### PR DESCRIPTION
**Pull request by lonyele**
When I tried to use DragLayer functionality, I've got into similar problem as #773, #811 and #780. DragLayer example has the code of its implementation at [DragLayer Example](https://github.com/react-dnd/react-dnd/tree/master/packages/documentation/examples/02%20Drag%20Around/Custom%20Drag%20Layer) , however I think documents can be improved thus I've made these changes. 

I want to clearly deliver 2 steps to do while user implements their own custom drag preview functionality.
1.  stop browser's default drag preview by using DragSourceConnector's dragPreview function.
2. make own customized drag layer by using DragLayer.

Let me know if something is wrong or wants me to do something more.

### CODE REVIEW

**Comment by lonyele** [comment]
hm... It looks too many commits with not so important things... Is It a time to rebase?  This is my first PR, so let me know If something is not sufficient.(I will learn and apply it)

**Comment by lonyele** [comment]
I'm sorry but this is my first PR. It looks like this PR is reviewed by @theTechie . But I can't do anything further(merging to original react-dnd repo or else..)  Is this something I have to merge? or one of the contributors who have authorization can only do.

  If anyone is busy, then It's ok. Just I don't know If there is something I should do more. As I know of merge should be done by one of contributors...

**Comment by AndrewJHart** [comment]
^This is a good bit of documentation that needs to be added - Can somebody please get back to reviewing this? @lonyele good work 👍

**Comment by ViggoV** [comment]
Very helpful extra information, but I still think something vital is missing.. I can't for the life of me figure out what a DragLayer component is supposed to be? The docs say that it is used for creating a custom drag preview, but not really what role it plays or where to put it. There is no real indication of why it is called a Drag _Layer_ since it seems to be there for the purpose of rendering custom previews and not much else.. I am very confused!

**Comment by augbog** [comment]
@ViggoV In case no one answered your question yet, the role of the `CustomDragLayer` is that you can have the ability to create your own custom drag preview with React. This is useful in cases where you might not want to reuse whatever DOM element you are rendering. An example in how we use it is in Evernote is the NoteList (which has little Note card snippets) and table rows are both places where we drag but the preview we make is consolidated so it looks like the same. We wouldn't want to reuse what is rendered in the DOM. 

In terms of where to put it, yeah I agree I think the documentation could be a little clearer about that. The DragLayer is generally a global you need at the top similar to many other components like `react-tooltip`. This way it can get rendered in and start automatically being used. Note you'll see BOTH the drag preview from your DragLayer and the default DOM unless you call `getEmptyImage` from the `react-dnd-html5-backend` (assuming you're using it).

**Comment by lonyele** [comment]
@ViggoV  hm...  what about this?  Think of it as a tooltip, modal or toast. You trigger these by clicking button or hovering on html element or from whatever actions(In this case, It is a dragging) and it shows on top of everything. The word "Layer", you can think of it as a photoshop's layer system, z-index from css, or something like why react-portal can be useful. Literally, It is a layer that is in charge of showing react component/information when drag and drop is going on.

**Comment by ovflowd** [comment]
Just wondering if this could be reopened and continued to be working. The docs miss a lot of important information about connectors, previews and the "custom drag layer".

@augbog I believe it's called "layer" because indeed it creates a layer where the drag stuff happens. If you inspect, during drag an element is created. That's why on my scenario I add eg.: `position: fixed` that's also why I used `translate3d` in order to move the object. It's indeed a layer where the "drag" actually happens.

On my case I had to change the default preview to a blank image since **BOTH** previews are happening and I don't know how to actually remove the original one.

Also using a Custom Drag Layer I'm not sure how to make the animation of the element going back to start position if I try to drop in an invalid target.

Anyways those docs could really help...

**Pull request closed without merging**
