### PR TITLE
do not attach refs on the stateless components

### LINKED ISSUE #896: React 16 - Update: Warning: Stateless function components cannot be given refs.
Currently updated my project to React v16.0.0 from v15.6.2, and ran into this compatibility issue.

It appears that when the `DecoratedComponent` wrapped by `DragDropContext` and `DragSource` uses ref in React v16.0.0, this error is thrown. Error persists even if I refactor the component from stateless to class-based.

```js
warning.js:33 Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.

Check the render method of `DragDropContext(withRouter(Board))`.
    in withRouter(Board) (created by DragDropContext(withRouter(Board)))
    in DragDropContext(withRouter(Board)) (created by Cards)
...
```

package versions
* `react@^16.0.0`
* `react-dom@^16.0.0`
* `react-dnd@^2.5.3`
* `react-router@4.1.2`

### PR DESCRIPTION
**Pull request by knowbody**
This fixes #896

### CODE REVIEW

**Comment by knowbody** [comment]
@darthtrevino is there any chance to get this merged (if it's ok) and cut the new release? Currently this is the only library stopping me from using React v16. Thank you!

**Comment by jmdelcarmen** [comment]
@knowbody same. Hopefully this gets noticed, and merged soon.

**Comment by zelanter** [comment]
@knowbody same here.

**Comment by davidworkman9** [comment]
Has this been released? I'm still getting this error on 2.5.4.

**Comment by knowbody** [comment]
@davidworkman9 it's been released, and I do not get this error again.

**Comment by davidworkman9** [comment]
@knowbody, weird.. I just made a brand new folder, ran `npm install react-dnd` in it, and I get `2.5.4` but the file `/lib/DragDropContext.js` does not have any mention of `render` except for the render function for `DragDropContextContainer`.

screen shot 2017-10-30 at 8 37 03 am

**Comment by knowbody** [comment]
@davidworkman9 see my PR changes above. The changes are bing applied on `decorateHandler.js` which deals with the `refs`

**Comment by davidworkman9** [comment]
Ok sorry, I didn't look at the file name in your PR, just the code. I guess I'm having a different issue, but I have the same error message as in #896.
```
Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.

Check the render method of `DragDropContext(Component)`.
    in Unknown (created by DragDropContext(Component))
```
code:
```
const DraggableContainer = DragDropContext(HTML5Backend)(() => <div />);
```

**Comment by knowbody** [comment]
do you mind creating a failing test case as a separate repo or in the https://codesandbox.io and I will try to look into it in the evening

**Comment by davidworkman9** [comment]
[Here's a   @@codesandbox](https://codesandbox.io/s/14wj6l8n34), Thanks!

**Comment by mertkahyaoglu** [comment]
I'm also getting this error with v2.5.4.

**Comment by zunder** [comment]
@knowbody is there any update on this issue? Still having the error with the v2.5.4, codesandbox above demonstrates it pretty well.

**Pull request merged**
