### PR TITLE
Add react-dnd-touch-backend

### LINKED ISSUE #1363: Merge in react-dnd-touch-backend
Hi guys,

I maintain https://github.com/yahoo/react-dnd-touch-backend and am thinking of merging that into this monorepo to further optimize the maintenance cost personally. If you guys are open to that, let me know what needs to be done to fit in your toolchain.

Cheers,

LH

### PR DESCRIPTION
**Pull request by darthtrevino**
Fixes #1363

### CODE REVIEW

**Comment by longlho** [comment]
Can we merge this in :) ?

**Comment by darthtrevino** [comment]
Yep! @longlho I made some updates to the TouchBackend to get it in line with our current TypeScript settings. I'll look into wiring it into the documentation so we can test out out further

**Comment by longlho** [comment]
thanks a lot!

**Comment by marvwhere** [comment]
Hey, I really would like to test it out. But I can't figure out right now, how to import the TouchBackend now.

    import TouchBackend from 'react-dnd-touch-backend';

will be now?

Thanks for all your great work

**Comment by marvwhere** [comment]
Hey question: 

My current Code:

    import { BackendFactory } from 'dnd-core';
    import TouchBackend from 'react-dnd-touch-backend';

    const Backend: BackendFactory = TouchBackend({
      enableMouseEvents: true
    });

    export default Backend;

This will not work anymore with 9.0.0 now and the mono-repo (which I think is excellent step) 

What do I need to do, to make it work again with:

    <DndProvider backend={Backend}>


Thanks for all your work.

**Comment by darthtrevino** [comment]
Hey Marvin,
The DndProvider in 9.0 accepts a new 'options' prop.

<DndProvider backend={TouchBackend} options={{ enableMouseEvents: true }}>

**Comment by leantide** [comment]
Hi,

`<DndProvider backend={TouchBackend({ delayTouchStart: 200 })}>` was working for me on react-dnd@8.0.3 with react-dnd-touch-backend@0.8.3. But this syntax caused an error on react-dnd@9.0.0 with react-dnd-touch-backend@9.0.0.

After changing over to use `<DndProvider backend={TouchBackend} option=({ delayTouchStart: 200 })>`, I no longer had the error.

Nevertheless, even with the new syntax to avoid the error, time drag and drop no longer works for me on my touch device.

For now I've reverted for now back to 8.03 / 0.8.3. Will try to upgrade again sometime. Thanks.

**Comment by darthtrevino** [comment]
@leantide would you be willing to put up a quick codesandbox demonstrating a working example? The touch-backend is fairly new in this repository, and I'd like to get that to a reliable point

**Comment by darthtrevino** [comment]
I can repro it on my end. I'll see if I can get this working tonight

**Comment by darthtrevino** [comment]
Thanks for the report @leantide - this should be fixed in the next patch releaes

**Comment by leantide** [comment]
Thanks @darthtrevino. Using <DndProvider backend={TouchBackend} options={{ delayTouchStart: 200 }}> now works for me on react-dnd-touch-backend @ 9.0.2.

Just a suggestion. Given that there are two backends, maybe it would be beneficial in your docs to show an example of how a web app could support both a mouse ainterface and touch interface, for example, by using a component that would dynamically use the HTML backend or the touch backend based on the detection of a mouse using 
`window.matchMedia('(pointer: fine)')` 
and the detection of touch using 
`window.matchMedia('(pointer: coarse)')`

**Pull request merged**
