### PR TITLE
fix: update wrapInTestContext to expose `getManager()` method

### PR DESCRIPTION
**Pull request by JKillian**
Tweaks the `wrapInTestContext` [as per this comment](https://github.com/react-dnd/react-dnd/issues/1506#issuecomment-537699644) so that it gives consumers an easy way to access the `DragDropManager` in their tests.

Also updates the testing instructions for Enzyme to show how to work around an enzyme bug in order to access the `DragDropManager`.

### CODE REVIEW

**Comment by JamesMHenderson** [comment]
How would you simulate the drag events?

**Comment by JKillian** [comment]
> How would you simulate the drag events?

Further changes to other components might also be necessary to make that possible, I haven't looked in to it. But figured might as well get the ball rolling on making things more testable with Enzyme!

**Comment by NYannick** [comment]
Hello any update on this fix ?

**Comment by darthtrevino** [comment]
LGTM!

**Pull request merged**
